version: 0.0
os: linux
files:
  - source: /build/
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: Scripts/before_install.sh
      timeout: 100
      runas: root
  AfterInstall:
    - location: Scripts/after_install.sh
      timeout: 100
      runas: root
  ValidateService:
    - location: Scripts/app_start.sh
      timeout: 100
      runas: root


#EXEMPLO DA AULA
#version: 0.0
#os: linux
#files:
#  - source: Config/config.txt
#    destination: /webapps/Config
#  - source: source
#    destination: /webapps/myApp
#hooks:
#  BeforeInstall:
#    - location: Scripts/UnzipResourceBundle.sh
#    - location: Scripts/UnzipDataBundle.sh
#  AfterInstall:
#    - location: Scripts/RunResourceTests.sh
#      timeout: 180
#  ApplicationStart:
#    - location: Scripts/RunFunctionalTests.sh
#      timeout: 3600
#  ValidateService:
#    - location: Scripts/MonitorService.sh
#      timeout: 3600
#      runas: codedeployuser
