version: 0.2

phases: 
  pre_build:
    commands:
      - echo Instalando dependencias
      - npm install
   
  build:
    commands:
      - echo Build iniciando em `date`
      - npm run build

  post_build:
    commands:
      - echo Build finalizado em `date`   
artifacts:
  files:
    - build/**/*
    - Scripts/**/*
    - appspec.yml




#EXEMPLO DA AULA
#version: 0.2
#phases:
#  pre_build:
#    commands:
#      - echo Instalando dependencias
#      - npm install
#  build:
#    commands:
#      - echo Build iniciado em 'date'
#      - npm run build
#  post_build:
#    commands:
#      - echo Build finalizando em 'date'
#artifacts:
#  files:
#    - build/**/*